### ISSUE TITLE
Change Position of ValueBox

### ISSUE THREAD

**Issue by max-zinn** [Mikhus/canvas-gauges#147]
Hi there,
it would be nice, if it was possible to change the position of the value box.
I'll make a fork for that, but I can't guarantee, that the pull Request comes in the next time..

EDIT:  
It would be also nice to change the positions of units and title, as well as the z-index of all those components

**Comment by max-zinn** [comment]
The Values of a horizontal linear gauge is not visible at all.

**Comment by max-zinn** [comment]
<img width="153" alt="bildschirmfoto 2017-11-03 um 15 37 09" src="https://user-images.githubusercontent.com/31882484/32379099-e344facc-c0ac-11e7-8ff3-176cb60b13ab.png">

<img width="413" alt="bildschirmfoto 2017-11-03 um 15 36 21" src="https://user-images.githubusercontent.com/31882484/32379067-cef533ac-c0ac-11e7-8f66-90efc08506a0.png">

As you can see here, if the gauge is drawn vertical, the value is visible, as expected. But when it is horizontal, it seems to get drawn below the canvas.
Could be fixed, if it was possible to change the positions of each component.

**Comment by saiyanx** [comment]
Did you use gradient for the vertical color scheme, looks pretty neat and did you find a solution for your problem?

**Comment by max-zinn** [comment]
Hi @saiyanx 
Yes I used a smooth gradient. I think it went from #000000 to #333333 but I'm not sure about that because I stopped working on that a long time ago.

I didn't have enough time back then to find a suitable solution that fits on more use-cases than mine. So I just went into the code and changed some numbers until it fit. 😆

**Comment by Mikhus** [comment]
Yes, by design it does not support value box for horizontal linear gauge, as far as I did not found a good way to implement it. BTW there are several ways to do thet. First one is described above - is to fork and change the code. Another one is to use [drawing injections](https://canvas-gauges.com/documentation/user-guide/scripting-api#injecting-into-gauge-drawing-workflow) to draw whatever you want on the gauge without base code change.
